### ISSUE TITLE
libxl.h: No such file or directory

### ISSUE THREAD

**Issue by gajus** [DirtyHairy/node-libxl#24]
All my builds started to suddenly break with "libxl.h: No such file or directory" error.

```
$ npm i

> libxl@0.4.0 install /srv/node_modules/libxl
> node install-libxl.js && node-gyp rebuild

Downloading http://www.libxl.com/download/libxl-lin-latest.tar.gz
successfully downloaded /tmp/tmp-137N6qoM5vqOgRzlibxl-lin-latest.tar.gz, MD5: b684a69cb0e9bac91e38b8316e35690e
Extracting /tmp/tmp-137N6qoM5vqOgRzlibxl-lin-latest.tar.gz ...
make: Entering directory '/srv/node_modules/libxl/build'
  CXX(target) Release/obj.target/liblibxl/src/bindings.o
In file included from ../src/bindings.cc:25:0:
../src/common.h:27:19: fatal error: libxl.h: No such file or directory
 #include <libxl.h>
                   ^
compilation terminated.
liblibxl.target.mk:118: recipe for target 'Release/obj.target/liblibxl/src/bindings.o' failed
make: *** [Release/obj.target/liblibxl/src/bindings.o] Error 1
make: Leaving directory '/srv/node_modules/libxl/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/node_modules/libxl
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxl@0.4.0 install: `node install-libxl.js && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxl@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/smith/.npm/_logs/2019-09-24T03_30_45_491Z-debug.log

```

It is not clear what is causing this: Node.js version didn't change, libxl NPM version didn't change and as far as I can tell, the contents of `libxl-lin-latest.tar.gz` hasn't changed either.

Any suggestions?

**Comment by gajus** [comment]
Can be replicated with:

```Dockerfile
FROM node:12

RUN npm install libxl

```

```bash
$ docker build .

```

**Comment by DirtyHairy** [comment]
Thanks for the alert. Seems this is caused by a change in `tar@4.4.11` --- it fails to decompress the libxl tarball. I have released 0.4.1 which pins tar to 4.4.10 (that one works fine). I'll do a similar 0.3 release later tonight.

**Comment by DirtyHairy** [comment]
Without further looking (have to leave now), this looks like https://github.com/npm/node-tar/issues/232 😛

**Comment by gajus** [comment]
Thank you
