### ISSUE TITLE
"Error: unable to load libxl.node" doesnt show real problem

### ISSUE THREAD

**Issue by i4got10** [DirtyHairy/node-libxl#3]
Im trying to find the reason why lib not working and add console.log to watch that going wrong

``` javascript
for (var i = 0; i < paths.length; i++) {
    try {
        bindings = require(path.join(paths[i], 'libxl'));
        break;
    } catch (e) {
        console.log(e);
    }
}
```

first is that `paths` is `[ undefined ]`, so we can pass it with

```
var paths = process.env['NODE_LIBXL_PATH'] ? [process.env['NODE_LIBXL_PATH']] : [];
```

second it could be better to show the truth reason of library fail

``` javascript
        if (e.code !== 'MODULE_NOT_FOUND') {
            throw e;
        }
```

LOGS

```
[TypeError: Arguments to path.join must be strings]

{ [Error: Cannot find module '/Users/frgt/Projects/metgen/node_modules/libxl/lib/darwin-x64/libxl'] code: 'MODULE_NOT_FOUND' }

{ [Error: Cannot find module '/Users/frgt/Projects/metgen/node_modules/libxl/lib/darwin/libxl'] code: 'MODULE_NOT_FOUND' }

{ [Error: Cannot find module '/Users/frgt/Projects/metgen/node_modules/libxl/build/Debug/libxl'] code: 'MODULE_NOT_FOUND' }

[Error: dlopen(/Users/frgt/Projects/metgen/node_modules/libxl/build/Release/libxl.node, 1): Library not loaded: libxl.dylib
  Referenced from: /Users/frgt/Projects/metgen/node_modules/libxl/build/Release/libxl.node
  Reason: image not found]
```

**Comment by chidalgogalvez** [comment]
y cual es la solución?

**Comment by gajus** [comment]
@DirtyHairy I am confused what is the solution for this too. I am getting the "image not found" error.

I am assuming that "image not found" error is referring to not being able to find `/node_modules/libxl/deps/libxl/lib/libxl.dylib`.

**Comment by gajus** [comment]
There isn't "libxl.node" file anywhere that I can see though.

**Comment by gajus** [comment]
```js
require('/Users/gajus/Documents/dev/[..]/node_modules/libxl/build/Release/libxl.node');

```

is giving:

```
internal/modules/cjs/loader.js:977
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/gajus/Documents/dev/[..]/node_modules/libxl/build/Release/libxl.node, 1): Library not loaded: libxl.dylib
  Referenced from: /Users/gajus/Documents/dev/[..]/node_modules/libxl/build/Release//libxl.node
  Reason: image not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:977:18)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/gajus/Documents/dev/[..]/node_modules/libxl/lib/libxl.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)

```

**Comment by gajus** [comment]
`libxl.dylib` needs to be copied to the current working directory or path to `libxl.dylib` must be added to `DYLD_LIBRARY_PATH`.

Upon second reading, this is clearly explained in https://github.com/DirtyHairy/node-libxl#compilation-phase
